//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BebachModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beba()
        {
            this.Aktivnosts = new HashSet<Aktivnost>();
            this.Pregleds = new HashSet<Pregled>();
            this.Slikas = new HashSet<Slika>();
        }
    
        public int ID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<System.DateTime> Dat_rod { get; set; }
        public string OIB { get; set; }
        public string Adresa { get; set; }
        public string Majka { get; set; }
        public string Otac { get; set; }
        public Nullable<System.DateTime> Dat_kreiranja { get; set; }
        public Nullable<System.DateTime> Dat_azu { get; set; }
        public string Unio { get; set; }
        public Nullable<bool> Aktivan { get; set; }
        public string Racun { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aktivnost> Aktivnosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregled> Pregleds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slika> Slikas { get; set; }
    }
}
